### ISSUE TITLE
allow to specify more url other than content page

### ISSUE THREAD

**Issue by teschmitz** [collective/collective.portlet.content#6]
Similar to the static text portlet, I would like to be able to specify a URL to link to via the More... link and the portlet header.

That would, of course, mean that the user is offered 3 options:
1) no link (neither from header nor footer)
2) link to content page
3) link to specified page

**Comment by regebro** [comment]
IMO, what you then want is rather a static text portlet where you can edit the text with the rich-text editor, rather than this portlet. It's specifically designed to show off existing content. Having the link go somewhere else than that content doesn't make any sense.

I suggest closing as "wontfix".

**Comment by khink** [comment]
I agree.

**Comment by regebro** [comment]
At least, since one of the points with this is that you can have multilingual content, you need one link per language, and then you have to have the link in the content anyway. Closing.
